# Header
menu:
  主页: /
  所有文章: /archives
  Categories: categories
  Tags: tags
  About: about


#主页中的话
index:
  welcome: 'Be the change you want to see in the world.'
  about: 关于我，热爱coding，喜欢思考，喜欢长跑，星际争霸2
  works: 这里展示了一些我以前的作品，以及我最近正在填的坑...
  notes: 这里是我的最近的一些笔记，有自己在coding中的感悟，也有从其他地方转载的好文章。
  contact: 假如你想要联系我，请Email我，或者给我留言。



#主页图片URL，home的图片如果需要替换，直接替换img中的home.png即可
pictures:
  about: img/about.jpg
  contact: img/contact.jpg

#你的社交
contact:
  github: https://github.com/ForeverSc
  mail: fengshuochn@126.com

#你的头像url
avatar: img/avatar.jpg

#你的座右铭
motto: 'thinking&coding'

#works的URL
works:
  work_1: https://github.com/ForeverSc/hexo-theme-forever
  work_2: https://github.com/ForeverSc/CCNUChiSha
  work_3: https://github.com/ForeverSc/NewIOTSystem
  work_4: https://github.com/ForeverSc

#多说评论
duoshuo: 'fengshuochn'
